/*
  # Add short_code to invoice_links

  ## Summary
  Adds a short alphanumeric code to invoice_links rows so that customer-facing
  SMS/email links can use a short /i/{shortCode} URL instead of the full
  /customer-portal/{orderId}?t={token} URL.

  ## Changes
  ### Modified Tables
  - `invoice_links`
    - New column: `short_code` (text, nullable, unique)
      - Nullable so existing rows without a short code are unaffected
      - Uniqueness enforced by index
      - New links generated by send-invoice will always have a short code

  ## Notes
  - Existing invoice_links rows with no short_code will simply not be reachable
    via /i/ — their original ?t= links still work unchanged.
  - No backfill is performed; short codes are generated lazily for new/resent links.
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'invoice_links' AND column_name = 'short_code'
  ) THEN
    ALTER TABLE invoice_links ADD COLUMN short_code text;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS invoice_links_short_code_idx ON invoice_links(short_code)
  WHERE short_code IS NOT NULL;
